modLoader = "javafml" #mandatory
loaderVersion = "[0,)"# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license = "${mod_license}"
[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
issueTrackerURL="https://github.com/oierbravo/mechanical-trading-station-mod/issues"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="mechanicals_lib.png" #optional
logoFile="logo.png"
credits="Code inspiration from the amazing Create mod"
authors = "${mod_author}" #optional
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId = "create"
mandatory = true
versionRange="[6.0.4,6.1.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "trading_station"
mandatory = true
versionRange="[1.0.0,1.1.0)"
ordering = "AFTER"
side = "BOTH"