
#Settings for the trading_station
[trading_station]
	#How much progress per tick
	#Range: > 1
	progressPerTick = 1

#Settings for the Powered Trading Station
[powered_trading_station]
	#How much progress per tick
	#Range: > 1
	progressPerTick = 1
	#How much energy capacity has
	#Range: > 1
	energyCapacity = 64000
	#How much energy can transfer
	#Range: > 1
	energyTransfer = 200
	#How much energy consumens per tick
	#Range: > 1
	energyPerTick = 1000

